baseURL = 'https://rotteperdute.it/'
languageCode = 'it-it'
title = 'Rotte Perdute Traduzioni'
theme = 'paper'

[Params]
favicon = '/immagini/loghi/logo_favicon.png'

[[menu.main]]
name = 'Home'
url = '/'
weight = 0

[[menu.main]]
name = 'Chi Siamo'
url = '/chi-siamo/'
weight = 1
